apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-storageos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-storageos
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-storageos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-storageos
subjects:
- kind: ServiceAccount
  name: secret-storageos
  namespace: storageos
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-storageos
  labels:
    app: secret-storageos
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: secret-storageos
    spec:
      serviceAccount: secret-storageos
      containers:
      - image: cvando/kube-nginx-letsencrypt:latest
        name: secret-storageos
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/kubernetes/ssl
        name: ssl-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
               - key: node-role.kubernetes.io/etcd
                  operator: In
                  values:
                  - "true"
      restartPolicy: Never
      tolerations:
      - key: "node-role.kubernetes.io/controlplane"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "node.cloudprovider.kubernetes.io/uninitialized"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      volumes:
      - name: ssl-volume
        hostPath:
          path: /etc/kubernetes/ssl
